name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-macOS:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and test
      run: xcodebuild clean build test -project feed-app.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
  build-and-test-iOS:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and test
      run: xcodebuild clean build test -project feed-app.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

